spring.application.name=hub_estudos

//spring.datasource.url=${URL_POSTGRES}
//spring.datasource.username=${USUARIO_POSTGRES}
//spring.datasource.password=${SENHA_POSTGRES}

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0&preparedStatementCacheQueries=0
spring.datasource.username=postgres.qsgniceqmykhutibmolz
spring.datasource.password=CiYGlGzf5kWv7S6I


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8081